name: 'PR Review Slack Reactions'
description: 'Automatically add emoji reactions to Slack messages when PRs are reviewed, approved, or merged'
author: 'Wispr AI'

branding:
  icon: 'message-circle'
  color: 'blue'

inputs:
  slack-bot-token:
    description: 'Slack Bot User OAuth Token (starts with xoxb-)'
    required: true
  slack-channel-id:
    description: 'Slack channel ID where PR reviews are posted'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: false
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        if [ ! -d "node_modules" ]; then
          npm ci --prefer-offline --no-audit
        fi

    - name: Build TypeScript
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        if [ ! -d "dist" ]; then
          npm run build
        fi

    - name: Determine event type and run bot
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        SLACK_BOT_TOKEN: ${{ inputs.slack-bot-token }}
        SLACK_CHANNEL_ID: ${{ inputs.slack-channel-id }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Extract PR URL based on event type
        if [[ "${{ github.event_name }}" == "check_suite" ]]; then
          # GitHub embeds the associated PRs directly in the check_suite event —
          # this is the authoritative association, no API call needed.
          PULL_REQUESTS='${{ toJSON(github.event.check_suite.pull_requests) }}'
          PR_NUMBER=$(echo "$PULL_REQUESTS" | jq -r '.[0].number // empty')

          if [[ -z "$PR_NUMBER" ]]; then
            # Fallback: look up by head SHA, but only consider open PRs
            PR_NUMBER=$(curl -s \
              -H "Authorization: token ${{ inputs.github-token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.check_suite.head_sha }}/pulls" \
              | jq -r 'map(select(.state == "open")) | .[0].number // empty')
          else
            # Embedded PR objects don't include state — verify the PR is still open
            # to avoid racing with merge events that haven't been processed yet.
            PR_STATE=$(curl -s \
              -H "Authorization: token ${{ inputs.github-token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" \
              | jq -r '.state // empty')
            if [[ "$PR_STATE" != "open" ]]; then
              echo "PR #$PR_NUMBER is $PR_STATE (not open), skipping"
              exit 0
            fi
          fi

          if [[ -z "$PR_NUMBER" ]]; then
            echo "No open PR found for this commit, skipping"
            exit 0
          fi

          PR_URL="https://github.com/${{ github.repository }}/pull/$PR_NUMBER"

        elif [[ "${{ github.event_name }}" == "status" ]]; then
          # Status events only carry the commit SHA — look up the open PR for it
          PR_NUMBER=$(curl -s \
            -H "Authorization: token ${{ inputs.github-token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.sha }}/pulls" \
            | jq -r 'map(select(.state == "open")) | .[0].number // empty')

          if [[ -z "$PR_NUMBER" ]]; then
            echo "No open PR found for this commit, skipping"
            exit 0
          fi

          PR_URL="https://github.com/${{ github.repository }}/pull/$PR_NUMBER"

        else
          PR_URL="${{ github.event.pull_request.html_url }}"
        fi

        # Determine event type
        if [[ "${{ github.event_name }}" == "pull_request" ]] && [[ "${{ github.event.action }}" == "closed" ]] && [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
          EVENT_TYPE="merged"
        elif [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
          REVIEW_BODY="${{ github.event.review.body }}"
          if [[ "${{ github.event.review.state }}" == "approved" ]]; then
            # Check if review has comments
            if [[ -n "$REVIEW_BODY" ]]; then
              EVENT_TYPE="review_approved_with_comments"
            else
              EVENT_TYPE="review_approved"
            fi
          elif [[ "${{ github.event.review.state }}" == "commented" ]]; then
            EVENT_TYPE="review_commented"
          else
            echo "Ignoring review state: ${{ github.event.review.state }}"
            exit 0
          fi
        elif [[ "${{ github.event_name }}" == "check_suite" ]]; then
          # Check if this is from CircleCI
          if [[ "${{ github.event.check_suite.app.slug }}" == "circleci" ]]; then
            if [[ "${{ github.event.action }}" == "completed" ]]; then
              if [[ "${{ github.event.check_suite.conclusion }}" == "success" ]]; then
                EVENT_TYPE="circleci_pass"
              elif [[ "${{ github.event.check_suite.conclusion }}" == "failure" ]]; then
                EVENT_TYPE="circleci_fail"
              else
                echo "Ignoring check_suite conclusion: ${{ github.event.check_suite.conclusion }}"
                exit 0
              fi
            elif [[ "${{ github.event.action }}" == "requested" ]] || [[ "${{ github.event.action }}" == "in_progress" ]]; then
              EVENT_TYPE="circleci_running"
            else
              echo "Ignoring check_suite action: ${{ github.event.action }}"
              exit 0
            fi
          else
            echo "Ignoring check_suite from: ${{ github.event.check_suite.app.slug }}"
            exit 0
          fi
        elif [[ "${{ github.event_name }}" == "status" ]]; then
          # Check if this is from CircleCI (commit status API)
          if [[ "${{ github.event.context }}" == *"circleci"* ]]; then
            if [[ "${{ github.event.state }}" == "success" ]]; then
              EVENT_TYPE="circleci_pass"
            elif [[ "${{ github.event.state }}" == "failure" ]] || [[ "${{ github.event.state }}" == "error" ]]; then
              EVENT_TYPE="circleci_fail"
            elif [[ "${{ github.event.state }}" == "pending" ]]; then
              EVENT_TYPE="circleci_running"
            else
              echo "Ignoring status state: ${{ github.event.state }}"
              exit 0
            fi
          else
            echo "Ignoring status from: ${{ github.event.context }}"
            exit 0
          fi
        else
          echo "Ignoring event: ${{ github.event_name }} / ${{ github.event.action }}"
          exit 0
        fi

        echo "Event type: $EVENT_TYPE"
        echo "PR URL: $PR_URL"

        # Run the bot
        EVENT_TYPE=$EVENT_TYPE PR_URL=$PR_URL node dist/index.js
